spring.application.name=banking_App
spring.datasource.url=jdbc:mysql://localhost:3306/banking_app
spring.datasource.username=root
spring.datasource.password=Prabhat@#1234
spring.jpa.hibernate.ddl-auto=update
